### PR TITLE
openstack: Add attribute OPENSTACK_INSTANCE_UUID

### LINKED ISSUE #930: Afterburn reports incorrect OpenStack instance id
# Bug #
```
[root@mbooth-centos-9 ~]# afterburn --provider openstack --attributes afterburn
[root@mbooth-centos-9 ~]# cat afterburn
AFTERBURN_OPENSTACK_INSTANCE_ID=i-062839a6
...
```

This instance id is meaningless. It is returned by the legacy ec2 metadata service which is deep frozen so we can't even fix it in OpenStack.

The issue is that it's using the wrong metadata endpoint: https://github.com/coreos/afterburn/blob/f22131c775094c559baf5c5d712425f341f3556e/src/providers/openstack/network.rs#L11-L12

It should probably be using a pinned version of the openstack metadata, e.g.:

```
[cloud-user@mbooth-centos-9 ~]$ curl -s http://169.254.169.254/openstack/2018-08-27/meta_data.json | jq
```
```json
{
  "uuid": "4037a55b-bcca-4a53-a596-c0155afe2642",
  "public_keys": {
    "mbooth-yubikey": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDBoTk3cat4yl1CFTkn75lfWqPWp96gVzpYqpWcLdj3fTUBZC9kFCbkcOkWRSXNB7eWr3ulLEAcyn0byeusT190GQ1rdlSyp6lYX9vLnPYbnfr8JzhX10B8LxSxVxj5JTCqIekBFco+rHO9h3GNF1DCyPIwDfPVl8cpL94g0Id7SVE4wH1GeVIkGoLxgt2R5WNdaxQH3Z4DclvXVwys/FMnkDUC2oTs24oxQMhcinpKaFA12LxWh+vv0+ALoGG6h6m0ka1ELFdHIXULEV5VM4dvMz8GFxvZWGzKHyjiaBsRGhO2takw/E+t/A2cFWhTqCggtK7k0ZEkUXQCbw7W4Q1JainElboCJinPEa7ErLnu0EwfOgIh0IfhyMd1UIAkkd2TAGUmiqpG5QjA/m36m1/CCrOWvyCHftmVOKxICRevzmZVCPSv1DCr3YpYwM7gdPKChACXQ8J4HBcPDNSUVTTHxklUpIqigmpwuZE/ohhs/mYRacPvEPGl+0lbmpuaCMK0e9mmm/0YhUqO9CjMNxShlWOo3hQhOl/kxtMduYmVPpePhE8ZYuaWkpUqVT1FuZ9LZzdWdp74Ero5cSpqHgLWZ7yt7g1JUzyu6xwWeMEQx5vJbD3fC2KBDZUmlica1wLX96dhcXYxjcdxMyGBpeEbScXU5WHJOsIx7DDi9HDu0w== cardno:18 280 175\n"
  },
  "keys": [
    {
      "name": "mbooth-yubikey",
      "type": "ssh",
      "data": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDBoTk3cat4yl1CFTkn75lfWqPWp96gVzpYqpWcLdj3fTUBZC9kFCbkcOkWRSXNB7eWr3ulLEAcyn0byeusT190GQ1rdlSyp6lYX9vLnPYbnfr8JzhX10B8LxSxVxj5JTCqIekBFco+rHO9h3GNF1DCyPIwDfPVl8cpL94g0Id7SVE4wH1GeVIkGoLxgt2R5WNdaxQH3Z4DclvXVwys/FMnkDUC2oTs24oxQMhcinpKaFA12LxWh+vv0+ALoGG6h6m0ka1ELFdHIXULEV5VM4dvMz8GFxvZWGzKHyjiaBsRGhO2takw/E+t/A2cFWhTqCggtK7k0ZEkUXQCbw7W4Q1JainElboCJinPEa7ErLnu0EwfOgIh0IfhyMd1UIAkkd2TAGUmiqpG5QjA/m36m1/CCrOWvyCHftmVOKxICRevzmZVCPSv1DCr3YpYwM7gdPKChACXQ8J4HBcPDNSUVTTHxklUpIqigmpwuZE/ohhs/mYRacPvEPGl+0lbmpuaCMK0e9mmm/0YhUqO9CjMNxShlWOo3hQhOl/kxtMduYmVPpePhE8ZYuaWkpUqVT1FuZ9LZzdWdp74Ero5cSpqHgLWZ7yt7g1JUzyu6xwWeMEQx5vJbD3fC2KBDZUmlica1wLX96dhcXYxjcdxMyGBpeEbScXU5WHJOsIx7DDi9HDu0w== cardno:18 280 175\n"
    }
  ],
  "hostname": "mbooth-centos-9",
  "name": "mbooth.centos-9",
  "launch_index": 0,
  "availability_zone": "nova",
  "random_seed": "Et5yhE5qtGfTg3Y4+BiKJ1hhj6uQRjprUgxz03BdJpOoINHc16jzbtV47+0byNUc5WUoN3MO4uVsW7iF9cjCrVM3mvdeDzGY7HilvG4ljKt1DIM8V6N9mfe7J+cfCn1W+rAzXHP47yduACsVmmqjax/BUNpP3DSRy7VCm0S3P37preTXGv2bJAQF5G9dt+cTZOup9ABg53VecaFaIoajMny/ggDvbAR6eKjv7gyXe2G9T9r+iZ/B7KHvwPZhgDzvqYhoF+2bB3BtmhNjOrv+Luilpf6jLAiAa/pY1pQIthvjOY1ExN0obl94VZ2T5hAxais47ZpX9GNCXUpqYOu5mIuWi/M8IjF4ubA5bMSKqs10bdgX2AHEASyc5WFiUJekratnt9lCqAQHuo9UgpTbXEFE7Ghw1O52nb14JTQmuvGfKac5I7b3wyHnBNyY9MJ+pemcclN+6B2tm9qKUT44+nyfu8rOSg/vmmsIQ6+WdDXY4Sg4COlnaoeMRwNQlkMdCvz0RhjaWMYJBl7Gtqy68maWeHMsqVw//g45FZyZS0TyY3tYaWlY96uidgWJhuaWeNLvHPDxIB3jW1V664OXMsQ7yVKikEYlx8S4AltjP4FEmp28R8y2Iusn9foyoulO6kW0HipoNXbKguXQ+FBRE0LnM3GAYcO0tmega4NADxk=",
  "project_id": "c73b7097d07c46f78eb4b4dcfbac5ca8",
  "devices": []
}
```

Unfortunately that doesn't make local IP information as easy to access (network_info.json doesn't contain IP information), so possibly some mix and match would be in order for local-ipv4 and public-ipv4.

## Operating System Version ##
This is a CentOS 9 mule, afterburn manually installed.

## Afterburn Version ##
This is afterburn-5.4.1-1.el9.x86_64, but also confirmed by code inspection on main.

### PR DESCRIPTION
**Pull request by pierreprinetti**
In the OpenStack attributes, the field `OPENSTACK_INSTANCE_ID` reports
the instance ID fetched from the EC2-compatibility-layer metadata.
However, that identifier (in the format `i-something`) does not match
the one used to refer to machines in the OpenStack API.

With this patch, I propose to add a new OpenStack attribute
`OPENSTACK_INSTANCE_UUID` that reports the actual identifier for
OpenStack instances in the context of the OpenStack API.

Implementation-wise, this patch adds enables fetching the UUID from both
the config-drive and from the Nova metadata service endpoint. In order
to retain compatibility with old versions of the metadata service, this
patch uses the old endpoint `2012-08-10`.

Fixes #930

### CODE REVIEW

**Comment by pierreprinetti** [comment]
I have tested this patch on an OpenStack VM.

**Metadata endpoint:**
```plaintext
$ ./afterburn --provider openstack --attributes ./attr-metadata.txt
May 26 09:23:19.498 WARN failed to locate config-drive, using the metadata service API instead
May 26 09:23:19.518 INFO Fetching http://169.254.169.254/openstack/2012-08-10/meta_data.json: Attempt #1
May 26 09:23:20.110 INFO Fetch successful
May 26 09:23:20.110 INFO Fetching http://169.254.169.254/latest/meta-data/hostname: Attempt #1
May 26 09:23:20.115 INFO Fetch successful
May 26 09:23:20.115 INFO Fetching http://169.254.169.254/latest/meta-data/instance-id: Attempt #1
May 26 09:23:20.120 INFO Fetch successful
May 26 09:23:20.120 INFO Fetching http://169.254.169.254/latest/meta-data/instance-type: Attempt #1
May 26 09:23:20.124 INFO Fetch successful
May 26 09:23:20.124 INFO Fetching http://169.254.169.254/latest/meta-data/local-ipv4: Attempt #1
May 26 09:23:20.129 INFO Fetch successful
May 26 09:23:20.129 INFO Fetching http://169.254.169.254/latest/meta-data/public-ipv4: Attempt #1
May 26 09:23:20.133 INFO Fetch successful
$ cat attr-metadata.txt
AFTERBURN_OPENSTACK_INSTANCE_TYPE=m1.medium
AFTERBURN_OPENSTACK_INSTANCE_ID=i-0000003b
AFTERBURN_OPENSTACK_IPV4_LOCAL=172.16.0.159
AFTERBURN_OPENSTACK_INSTANCE_UUID=4d7a54fe-95eb-4789-ac9a-3529618505ec
AFTERBURN_OPENSTACK_IPV4_PUBLIC=192.168.3.16
AFTERBURN_OPENSTACK_HOSTNAME=mule
```

**Config drive:**

```plaintext
# ./afterburn --provider openstack --attributes ./attr-cd.txt
# cat attr-cd.txt
AFTERBURN_OPENSTACK_INSTANCE_TYPE=m1.medium
AFTERBURN_OPENSTACK_IPV4_LOCAL=172.16.0.159
AFTERBURN_OPENSTACK_HOSTNAME=mule
AFTERBURN_OPENSTACK_INSTANCE_UUID=4d7a54fe-95eb-4789-ac9a-3529618505ec
AFTERBURN_OPENSTACK_IPV4_PUBLIC=
AFTERBURN_OPENSTACK_INSTANCE_ID=i-0000003b
```

**Comment by mdbooth** [comment]
Could do with a couple of unit tests (one each for network and config drive), but I think it's in good enough shape to remove the scary warning in the description.

I agree with the design decision to add a new parameter rather than fix the existing one. Although the existing value can't be used anywhere in the openstack API, it does still potentially serve as an opaque unique identifier: changing it could potentially break any server which had previously registered the old value.

**Comment by pierreprinetti** [comment]
>Could do with a couple of unit tests

Aaaand here they are!

**Comment by pierreprinetti** [comment]
I believe this patch to be ready for a review. Shall I assign @bgilbert?

File: src/providers/openstack/mock_tests.rs [hunk 1]
```diff
@@ -51,3 +51,58 @@ fn test_ssh_keys_404_ok() {
...
+fn test_instance_uuid() {
+    let mut server = mockito::Server::new();
+    let mut provider = OpenstackProviderNetwork::try_new().unwrap();
+    provider.client = provider.client.max_retries(0).mock_base_url(server.url());
+
+    server
+        .mock("GET", "/openstack/2012-08-10/meta_data.json")
+        .with_status(200)
+        .with_header("content-type", "application/json")
+        .with_body("{\"uuid\":\"abc-abc-abc\"}")
```
Comment (mdbooth) [inline src/providers/openstack/mock_tests.rs]: Similar to how we do it in gophercloud, I wonder if this should be a fixture containing some complete representative response.

Also an old battle scar reminds me to return valid uuids for things which should be uuids in tests 🤕

File: src/providers/openstack/mock_tests.rs
Comment (mdbooth) [inline src/providers/openstack/mock_tests.rs:1]: Could also do with a unit test for config drive.

File: src/providers/openstack/mock_tests.rs (hunk 1 above)
Comment (pierreprinetti) [reply src/providers/openstack/mock_tests.rs]: I was testing the function forgiveness in accepting IDs, with the assumption that if it can accept any string, then it will accept the canonical representation of a UUIDv4.
Do you think this test should match the current format of an instance ID exactly?

File: src/providers/openstack/mock_tests.rs
Comment (pierreprinetti) [reply src/providers/openstack/mock_tests.rs:1]: I added one assertion in the existing tests in configdrive.rs. Do you think I should cover more?

File: src/providers/openstack/mock_tests.rs (hunk 1 above)
Comment (mdbooth) [reply src/providers/openstack/mock_tests.rs]: Personally yes, and it should also be a complete response including a UUID. You could use the example output from the issue.

Comment (mdbooth) [reply src/providers/openstack/mock_tests.rs]: Scrap that, it should return the same fixture that the config drive is already using.

File: src/providers/openstack/mock_tests.rs
Comment (mdbooth) [reply src/providers/openstack/mock_tests.rs:1]: No, that's fine.

File: src/providers/openstack/mock_tests.rs (hunk 1 above)
Comment (pierreprinetti) [reply src/providers/openstack/mock_tests.rs]: I have added a JSON payload that comes from a request to that specific version of the Nova metadata (2012-08-10).

File: docs/usage/attributes.md [hunk 2]
```diff
@@ -93,13 +93,15 @@ Cloud providers with supported metadata endpoints and their respective attribute
   - AFTERBURN_OPENSTACK_HOSTNAME
   - AFTERBURN_OPENSTACK_IPV4_LOCAL
   - AFTERBURN_OPENSTACK_IPV4_PUBLIC
-  - AFTERBURN_OPENSTACK_INSTANCE_ID
+  - AFTERBURN_OPENSTACK_INSTANCE_ID (from the legacy EC2 metadata)
```
Comment (pierreprinetti) [inline docs/usage/attributes.md]: Is the EC2 metadata really legacy, @mdbooth ?

Comment (mdbooth) [reply docs/usage/attributes.md]: I'll defer to @stephenfin on that, but I'm comfortable saying it is.

File: src/providers/openstack/mock_tests.rs [hunk 3]
```diff
@@ -51,3 +51,58 @@ fn test_ssh_keys_404_ok() {
...
...E7T4xnrmT/T0ODQQbh6W+F+/mCSwOpRsZV0+FYcWg34InQM177eBweAv5Lwtct6B0xzCCXYpNTjWpBUe46dP7FO0ltzD57CGglRyx7whff96Og7Zx61/YfR/zrfI4NYiP+4EbiN24NuTn0DvND/anCpvA1Zpsd7bNMvL9YrlCRD2lfcQl3p6Kqi48jLNpqjEMYEmgYzzGjE1hFuVqdjY63bAmD3+NPlfARsgbMiPpLAmb3nE5FTCWktUTE8fnoWIojUYm7/4HoVQlwWxRhLKji5NiJGMgYw== cardno:9_040_793\n"}, "keys": [{"name": "pprinett", "type": "ssh", "data": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC/Zc+pyRoKWVS1CVx2soRe7Ia7RGkASpXZE495H2XuS3gF4Vb9JdATkJ4NURmAQhUN8TYCbfqTcf2Fpm/5mtG6Dn8Avua1mXgNRvrufVYBvWkOn9qPEYkwELSG0WcqjpISwsKRAU0d7Mcqo0aDmp/wpgbXHCBG03Q8w0uhRTdI7jEj/EzatbtkgUJnE79OHUImxdG+11oKH0Ul2lQlSo+pMa0fwS3GrHKIxxZmMckSpT+gua0AttuGpr+JYIZKNkoWn7bMqpYpJAlKxjzaB6ympaIAOgd/CxXnXPzc8ntIm/MubDUbGzo7dpq39MmxtWb1bahS/zeyFq0ZR43FbHexZyj21PiurtFOXl93r+wgBLBcVjBogi23p8i+SrjOVb+nJJ5XEUaLDYYE7T4xnrmT/T0ODQQbh6W+F+/mCSwOpRsZV0+FYcWg34InQM177eBweAv5Lwtct6B0xzCCXYpNTjWpBUe46dP7FO0ltzD57CGglRyx7whff96Og7Zx61/YfR/zrfI4NYiP+4EbiN24NuTn0DvND/anCpvA1Zpsd7bNMvL9YrlCRD2lfcQl3p6Kqi48jLNpqjEMYEmgYzzGjE1hFuVqdjY63bAmD3+NPlfARsgbMiPpLAmb3nE5FTCWktUTE8fnoWIojUYm7/4HoVQlwWxRhLKji5NiJGMgYw== cardno:9_040_793\n"}], "hostname": "mule", "name": "mule", "launch_index": 0, "availability_zone": "nova"}"#)
```
Comment (mdbooth) [inline src/providers/openstack/mock_tests.rs]: I'll leave this up to the maintainers, but given that there's already a fixtures directory containing related data I feel this blob would be better placed there and read from file.

File: docs/usage/attributes.md (hunk 2 above)
Comment (pierreprinetti) [reply docs/usage/attributes.md]: The [docs](https://docs.openstack.org/nova/latest/admin/metadata-service.html) don’t mention a deprecation. I’ll remove the word “legacy”, it doesn’t add anything anyway.

Comment (stephenfin) [reply docs/usage/attributes.md]: It's legacy insofar as it's no longer being updated and won't have any further updates. I guess you can think of it as deprecated but not deprecated for removal. With that said, you're probably right and noting this here doesn't really add anything.

Comment (pierreprinetti) [reply docs/usage/attributes.md]: Thank you for your informed advice @stephenfin. I’ll do that then.

File: src/providers/openstack/mock_tests.rs (hunk 3 above)
Comment (pierreprinetti) [reply src/providers/openstack/mock_tests.rs]: If I understand correctly, the fixture folder contains files meant to be passed to the tests as files. While we could move this string literal into a `.json` file and dynamically load it in the test, I wouldn't necessarily see that as an improvement.

**Review by lentzi90 — APPROVED** [review]
Looks good to me! I'm not familiar enough with the code base (or rust for that matter) to say anything about the specifics, but on a high level it looks like a good solution.
Thanks for working on this @pierreprinetti ! :slightly_smiling_face:

**Comment by mdbooth** [comment]
/lgtm

I'm hoping we can get an E2E test of this solving our root issue from @tormath1 later.

**Comment by tormath1** [comment]
FWIW I tested with a patched Flatcar image in the Cluster API OpenStack project - the UUID is fetched as expected (https://github.com/kubernetes-sigs/cluster-api-provider-openstack/pull/1564#issuecomment-1568701420).

**Comment by pierreprinetti** [comment]
@bgilbert @prestist Do you think we can get the tests executed, so that if there's anything failing I can maybe try and fix before you review?

**Comment by prestist** [comment]
@pierreprinetti

Firstly thank you for doing this!

Second, regarding your question about getting the tests working:
They are fixed by https://github.com/coreos/afterburn/pull/938
 
 If you do a `git push -f` it will re trigger all the CI. It looks like a simple re-run is not working at the moment.

**Comment by pierreprinetti** [comment]
>If you do a git push -f it will re trigger all the CI. It looks like a simple re-run is not working at the moment.

OK! I have run the below command in the expectation that the tests will now run:

```shell
git commit --amend --no-edit && git push --force
```

**Comment by pierreprinetti** [comment]
Are we missing an /ok-to-test label or something?

**Comment by prestist** [comment]
So since you have not contributed to the repo before it looks like GitHub wanted a maintainer to approve the CI for you to run. You can read about it here => https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks

File: docs/release-notes.md [hunk 4]
```diff
@@ -11,6 +11,7 @@ Major changes:
 
 Minor changes:
 
+- providers/openstack{,-metadata}: Add `OPENSTACK_INSTANCE_UUID` attributes
```
Comment (prestist) [inline docs/release-notes.md]: I think I would opt for this => WDYT? 


- openstack: Add `OPENSTACK_INSTANCE_UUID` attribute
- openstack-metadata: Add `OPENSTACK_INSTANCE_UUID` attribute

File: docs/usage/attributes.md [hunk 5]
```diff
@@ -93,13 +93,15 @@ Cloud providers with supported metadata endpoints and their respective attribute
   - AFTERBURN_OPENSTACK_HOSTNAME
   - AFTERBURN_OPENSTACK_IPV4_LOCAL
   - AFTERBURN_OPENSTACK_IPV4_PUBLIC
-  - AFTERBURN_OPENSTACK_INSTANCE_ID
+  - AFTERBURN_OPENSTACK_INSTANCE_ID (from the EC2 metadata)
```
Comment (prestist) [inline docs/usage/attributes.md]: hmm wdyt? 

AFTERBURN_OPENSTACK_INSTANCE_ID _EC2 metadata_
AFTERBURN_OPENSTACK_INSTANCE_UUID _Nova metadata_

File: src/providers/openstack/configdrive.rs [hunk 6]
```diff
@@ -37,6 +37,8 @@ pub struct MetadataEc2JSON {
 /// Partial object for openstack `meta_data.json`
 #[derive(Debug, Deserialize)]
 pub struct MetadataOpenstackJSON {
+    // Instance ID
```
Comment (prestist) [inline src/providers/openstack/configdrive.rs]: Could we add another '/' to conform with rest of comments? and a '.'

File: docs/usage/attributes.md (hunk 5 above)
Comment (prestist) [reply docs/usage/attributes.md]: Or is it more valuable to the end user to say which one is better for which version of openstack? 

IE. when ID should be used to fetch data from the EC2 or what version and newer should use the newer attribute?  x.y.z >= nova and x.y.z <= ec2

File: src/providers/openstack/configdrive.rs [hunk 7]
```diff
@@ -228,6 +233,10 @@ mod tests {
             "abai-fcos-afterburn-test"
         );
         assert_eq!(parsed.availability_zone.unwrap_or_default(), "nova");
+        assert_eq!(
+            parsed.uuid.unwrap_or_default(),
+            "b3c7f4de-da0b-44ae-a42c-fa3806b61d7f"
```
Comment (prestist) [inline src/providers/openstack/configdrive.rs:238]: Novice question, whats this uuid? is it standard or random default?

**Review by prestist — COMMENTED** [review]
Generally looks good to me, I have a few nits and a few questions. 

Thank you so much for putting this up!

File: docs/usage/attributes.md (hunk 5 above)
Comment (pierreprinetti) [reply docs/usage/attributes.md]: I don’t know of any reason to use the ID from the EC2 metadata when the Nova UUID is available.

I think that your first proposal makes most sense.

File: src/providers/openstack/configdrive.rs (hunk 7 above)
Comment (pierreprinetti) [reply src/providers/openstack/configdrive.rs:238]: It's the value that was already there [in the fixture](https://github.com/shiftstack/afterburn/blob/6418459606b0c6e2664a88d5a57552727c34c5d4/tests/fixtures/openstack-config-drive/openstack/meta_data.json#L4)

**Comment by pierreprinetti** [comment]
Thanks for the review, @prestist! I think I have applied all of your suggestions.

File: src/providers/openstack/mock_tests.rs (hunk 3 above)
Comment (bgilbert) [reply src/providers/openstack/mock_tests.rs]: I agree that this isn't especially legible here, and the fixture could be nice to reuse for additional tests in the future.  Let's move it into the fixtures directory and use `with_body_from_file()`.

File: src/providers/openstack/network.rs [hunk 8]
```diff
@@ -22,7 +31,21 @@ impl OpenstackProviderNetwork {
     }
 
     fn endpoint_for(key: &str) -> String {
```
Comment (bgilbert) [inline src/providers/openstack/network.rs]: Since we now have two classes of endpoints, it'd be clearer to rename this to e.g. `ec2_endpoint_for`.

File: docs/usage/attributes.md (hunk 5 above)
Comment (bgilbert) [reply docs/usage/attributes.md]: Apologies for the continued bikeshedding, but this feels a bit too brief for users who may not understand the distinction.  What about something like:

> - AFTERBURN_OPENSTACK_INSTANCE_ID &mdash; EC2-style instance ID, not used in OpenStack API
> - AFTERBURN_OPENSTACK_INSTANCE_UUID &mdash; OpenStack instance UUID (Afterburn &ge; 5.5.0)

File: src/providers/openstack/network.rs [hunk 9]
```diff
@@ -2,13 +2,22 @@
...
 use crate::retry;
 
-const URL: &str = "http://169.254.169.254/latest/meta-data";
+const EC2_URL: &str = "http://169.254.169.254/latest/meta-data";
+const NOVA_URL: &str = "http://169.254.169.254/openstack/2012-08-10/meta_data.json";
+
+/// Partial object for openstack `meta_data.json`
+#[derive(Debug, Deserialize, Default)]
+pub struct MetadataOpenstackJSON {
+    // Instance ID
```
Comment (bgilbert) [inline src/providers/openstack/network.rs]: Nit: `///` to make this a docstring.

**Review by bgilbert — COMMENTED** [review]
This looks good!  Thanks @pierreprinetti for the contribution and @mdbooth for the reviews.  Just a few nits and then I think we can land this.

**Comment by pierreprinetti** [comment]
Here's another try! Let's see if we get closer... :grin:

File: src/providers/openstack/mock_tests.rs [hunk 10]
```diff
@@ -51,3 +51,58 @@ fn test_ssh_keys_404_ok() {
...
+fn test_instance_uuid() {
+    let mut server = mockito::Server::new();
+    let mut provider = OpenstackProviderNetwork::try_new().unwrap();
+    provider.client = provider.client.max_retries(0).mock_base_url(server.url());
+
+    server
+        .mock("GET", "/openstack/2012-08-10/meta_data.json")
+        .with_status(200)
+        .with_header("content-type", "application/json")
+        .with_body_from_file("tests/fixtures/openstack-metadata/openstack/2012-08-10/meta_data.json")
```
Comment (bgilbert) [inline src/providers/openstack/mock_tests.rs]: This is failing the `cargo fmt` CI check.

**Review by bgilbert — COMMENTED** [review]
LGTM!

File: src/providers/openstack/mock_tests.rs (hunk 10 above)
Comment (pierreprinetti) [reply src/providers/openstack/mock_tests.rs]: woops.

**Review by bgilbert — APPROVED** [review]
