### PR TITLE
providers/*stack: allow 404 returns on *stack network provider

### LINKED ISSUE #662: openstack: afterburn-sshkeys service fails when no ssh key provided by metadata API
**Describe the bug**

It is valid to start instances in openstack without specifying an SSH key to provide with the metadata server (i.e. you can run `openstack server create` without specifying `--key-name=mykey`). However, if you do this with our current images the `afterburn-sshkeys@core.service` systemd unit fails because it's not properly handling the 404:

```
[core@d3 ~]$ systemctl status afterburn-sshkeys@core.service 
● afterburn-sshkeys@core.service - Afterburn (SSH Keys)
     Loaded: loaded (/usr/lib/systemd/system/afterburn-sshkeys@.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2020-11-04 17:44:01 UTC; 33s ago
    Process: 961 ExecStart=/usr/bin/afterburn ${AFTERBURN_OPT_PROVIDER} --ssh-keys=core (code=exited, status=1/FAILURE)
   Main PID: 961 (code=exited, status=1/FAILURE)

Nov 04 17:43:56 d3 afterburn[961]: Nov 04 17:43:56.730 INFO Failed to fetch: 404 Not Found
Nov 04 17:44:01 d3 afterburn[961]: Nov 04 17:44:01.730 INFO Fetching http://169.254.169.254/latest/meta-data/public-keys: Attempt #11
Nov 04 17:44:01 d3 afterburn[961]: Nov 04 17:44:01.939 INFO Failed to fetch: 404 Not Found
Nov 04 17:44:01 d3 afterburn[961]: Error: failed to run
Nov 04 17:44:01 d3 afterburn[961]: Caused by: writing ssh keys
Nov 04 17:44:01 d3 afterburn[961]: Caused by: maximum number of retries (10) reached
Nov 04 17:44:01 d3 afterburn[961]: Caused by: failed to fetch: 404 Not Found
Nov 04 17:44:01 d3 systemd[1]: afterburn-sshkeys@core.service: Main process exited, code=exited, status=1/FAILURE
Nov 04 17:44:01 d3 systemd[1]: afterburn-sshkeys@core.service: Failed with result 'exit-code'.
Nov 04 17:44:01 d3 systemd[1]: Failed to start Afterburn (SSH Keys).
```

The metadata service is there, though:

```
[core@d3 ~]$ curl http://169.254.169.254/latest; echo
meta-data/
user-data
```

So we just need to handle the 404 properly.

This was broken out of https://github.com/coreos/coreos-assembler/issues/1835

### PR DESCRIPTION
**Pull request by arithx**
Set `return_on_404` to `true` for the *stack network providers to handle the
`public-keys` not existing if an SSH key is not provided.

Closes: https://github.com/coreos/fedora-coreos-tracker/issues/662

### CODE REVIEW

**Comment by lucab** [comment]
LGTM, although it would be good to have a mock test for OpenStack metadata returning a 404 on `public-keys`, in order to help remembering where this is coming from and preventing regressions.

**Review by lucab — APPROVED** [review]

**Comment by dustymabe** [comment]
When you push the update do you mind updating the commit message to "fix" https://github.com/coreos/fedora-coreos-tracker/issues/662 ? I opened a separate issue to raise awareness in case anyone hits the issue and tries to find it in the tracker.

**Comment by dustymabe** [comment]
anything holding this up?

**Comment by arithx** [comment]
> anything holding this up?

I haven't had cycles to actually test the change or add the unit test.

File: src/providers/cloudstack/network.rs [hunk 1]
```diff
@@ -93,3 +97,62 @@ impl MetadataProvider for CloudstackNetwork {
...
+        provider.client = provider.client.max_retries(0);
+        provider.client = provider.client.return_on_404(false);
+
+        let _m = mockito::mock("GET", "/latest/meta-data/public-keys")
+            .with_status(404)
+            .create();
+        assert!(provider.ssh_keys().is_err());
+        mockito::reset();
+        provider.ssh_keys().unwrap_err();
+    }
```
Comment (arithx) [inline src/providers/cloudstack/network.rs]: I don't think we need this.

File: src/providers/openstack/network.rs [hunk 2]
```diff
@@ -102,3 +106,71 @@ impl MetadataProvider for OpenstackProviderNetwork {
...
+        provider.client = provider.client.max_retries(0);
+        provider.client = provider.client.return_on_404(false);
+
+        let _m = mockito::mock("GET", "/public-keys")
+            .with_status(404)
+            .create();
+        assert!(provider.ssh_keys().is_err());
+        mockito::reset();
+        provider.ssh_keys().unwrap_err();
+    }
```
Comment (arithx) [inline src/providers/openstack/network.rs]: I don't think we need this.

Comment (nikita-dubrovskii) [reply src/providers/openstack/network.rs]: done

File: src/providers/cloudstack/network.rs (hunk 1 above)
Comment (nikita-dubrovskii) [reply src/providers/cloudstack/network.rs]: done

File: src/providers/cloudstack/network.rs [hunk 3]
```diff
@@ -30,15 +30,19 @@ impl CloudstackNetwork {
     }
 
     fn endpoint_for(&self, key: &str) -> String {
-        format!("http://{}/latest/meta-data/{}", self.server_address, key)
+        format!("{}/latest/meta-data/{}", self.server_address, key)
     }
 
-    fn get_dhcp_server_address() -> Result<IpAddr> {
+    fn get_dhcp_server_address() -> Result<String> {
+        if cfg!(test) {
```
Comment (bgilbert) [inline src/providers/cloudstack/network.rs:37]: We usually make two separate function implementations, one `test` and one `not(test)`.

File: src/providers/cloudstack/network.rs [hunk 4]
```diff
@@ -14,7 +14,7 @@ const SERVER_ADDRESS: &str = "SERVER_ADDRESS";
 
 #[derive(Clone, Debug)]
 pub struct CloudstackNetwork {
-    server_address: IpAddr,
+    server_address: String,
```
Comment (bgilbert) [inline src/providers/cloudstack/network.rs]: This is an URL now, not an address, so should probably be renamed to `server_base_url` or similar.

File: src/providers/cloudstack/network.rs [hunk 5]
```diff
@@ -30,15 +30,19 @@ impl CloudstackNetwork {
     }
 
     fn endpoint_for(&self, key: &str) -> String {
-        format!("http://{}/latest/meta-data/{}", self.server_address, key)
+        format!("{}/latest/meta-data/{}", self.server_address, key)
     }
 
-    fn get_dhcp_server_address() -> Result<IpAddr> {
+    fn get_dhcp_server_address() -> Result<String> {
```
Comment (bgilbert) [inline src/providers/cloudstack/network.rs]: `get_server_base_url_from_dhcp()`?

File: src/providers/cloudstack/network.rs [hunk 6]
```diff
@@ -30,15 +30,19 @@ impl CloudstackNetwork {
...
+        if cfg!(test) {
+            #[cfg(test)]
+            return Ok(mockito::server_url());
+        }
         let server = util::dns_lease_key_lookup(SERVER_ADDRESS)?;
         let ip = server
             .parse()
             .chain_err(|| format!("failed to parse server ip address: {}", server))?;
-        Ok(IpAddr::V4(ip))
+        Ok(format!("http://{}", IpAddr::V4(ip).to_string()))
```
Comment (bgilbert) [inline src/providers/cloudstack/network.rs]: We shouldn't need to wrap `ip` in an `IpAddr` before stringifying it.

File: src/providers/cloudstack/network.rs [hunk 7]
```diff
@@ -93,3 +97,48 @@ impl MetadataProvider for CloudstackNetwork {
...
+        let key2 = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDj6FBVgkTt7/DB93VVLk6304Nx7WUjLBJDSCh38zjCimHUpeo9uYDxflfu2N1CLtrSImIKBVP/JRy9g7K4zmRAH/wXw2UxYziX+hZoFIpbW3GmYQqhjx2lDvIRXJI7blhHhTUNWX5f10lFAYOLqA9J859AB1w7ND09+MS3jQgSazCx17h+QZ0qQ6kLSfnXw9PMUOE1Xba9hD1nYj14ryTVj9jrFPMFuUfXdb/G9lsDJ+cGvdE2/RMuPfDmEdo04zvZ5fQJJKvS7OyAuYev4Y+JC8MhEr756ITDZ17yq4BEMo/8rNPxZ5Von/8xnvry+8/2C3ep9rZyHtCwpRb6WT6TndV2ddXKhEIneyd1XiOcWPJguHj5vSoMN3mo8k2PvznGauvxBstvpjUSFLQu869/ZQwyMnbQi3wnkJk5CpLXePXn1J9njocJjt8+SKGijmmIAsmYosx8gmmu3H1mvq9Wi0qqWDITMm+J24AZBEPBhwVrjhLZb5MKxylF6JFJJBs= root@example2";
+
+        let _m = mockito::mock("GET", "/latest/meta-data/public-keys")
+            .with_status(200)
+            .with_body(format!("{}\n{}", key1, key2))
+            .create();
+
+        let keys = provider.ssh_keys().unwrap();
+        assert_ne!(keys, vec![]);
```
Comment (bgilbert) [inline src/providers/cloudstack/network.rs]: Seems redundant with the next line?

File: src/providers/openstack/network.rs [hunk 8]
```diff
@@ -8,8 +8,6 @@ use crate::errors::*;
 use crate::providers::MetadataProvider;
 use crate::retry;
 
-const URL: &str = "http://169.254.169.254/latest/meta-data";
```
Comment (bgilbert) [inline src/providers/openstack/network.rs:11]: Why eliminate the constant?

File: src/providers/openstack/network.rs [hunk 9]
```diff
@@ -102,3 +106,57 @@ impl MetadataProvider for OpenstackProviderNetwork {
...
+        for (endpoint, body) in endpoints {
+            let m = mockito::mock("GET", endpoint)
+                .with_status(200)
+                .with_body(body)
+                .create();
+            mocks.push(m)
+        }
+
+        let keys = provider.ssh_keys().unwrap();
+        assert_ne!(keys, vec![]);
```
Comment (bgilbert) [inline src/providers/openstack/network.rs]: Likewise seems redundant.

File: src/providers/cloudstack/network.rs [hunk 10]
```diff
@@ -93,3 +97,48 @@ impl MetadataProvider for CloudstackNetwork {
         }
     }
 }
+
+#[cfg(test)]
+mod tests {
```
Comment (bgilbert) [inline src/providers/cloudstack/network.rs]: The other providers put their mock tests in a separate `mock_tests.rs` file.  We should probably do the same.

File: src/providers/cloudstack/network.rs (hunk 3 above)
Comment (nikita-dubrovskii) [reply src/providers/cloudstack/network.rs:37]: Yep, but than `cargo test` complains about unused imports and never-called functions. I wasn't sure if it's Ok to see such warnings during `test`.

File: src/providers/openstack/network.rs (hunk 9 above)
Comment (nikita-dubrovskii) [reply src/providers/openstack/network.rs]: done

File: src/providers/cloudstack/network.rs (hunk 10 above)
Comment (nikita-dubrovskii) [reply src/providers/cloudstack/network.rs]: done

File: src/providers/openstack/network.rs (hunk 8 above)
Comment (nikita-dubrovskii) [reply src/providers/openstack/network.rs:11]: did revert

**Review by bgilbert — APPROVED** [review]
