### PR TITLE
providers/azure: switch SSH key retrieval from certs endpoint to IMDS

### LINKED ISSUE #1217: Afterburn can no longer fetch ssh public keys from Azure API Endpoint
# Bug #

Afterburn can no longer fetch ssh public keys from Azure API Endpoint

## Operating System Version ##
Fedora CoreOS 42.20250512.3.0
## Afterburn Version ##
afterburn-5.7.0-4.fc42.x86_64 
## Environment ##
Azure

## Expected Behavior ##
ssh keys are deployed by afterburn

## Actual Behavior ##
no ssh keys are deployed

## Reproduction Steps ##

  1. run afterburn --cmdline --ssh-keys=core

## Other Information ##
it seems that the ssh public key is no longer included in the comp=certificates response.
I did not find a chain at all in the encrypted pkcs12.
This worked one or two weeks ago with the same VM image.

### PR DESCRIPTION
**Pull request by marmijo**
Azure no longer reliably provides SSH public keys in the goal-state certificates endpoints (`comp=certificates`) but Azure VM provisioning populates keys in the Instance Metadata Service (IMDS) under `compute/publicKeys`.

Update the Azure provider ssh key retrieval to remove the deprecated certificates flow. Instead, query the IMDS and parse the returned keyData entries into `PublicKey`s.

Fixes: https://github.com/coreos/afterburn/issues/1217

### CODE REVIEW

**Comment by travier** [comment]
Thanks! Do you have a docs/blog post reference for that change that we could link here?

**Review by travier — APPROVED** [review]
Completely untested but looks sane

**Comment by travier** [comment]
Should we add a `Fixes: https://github.com/coreos/afterburn/issues/1217` in this PR?

File: src/providers/microsoft/azure/mod.rs [hunk 1]
```diff
@@ -351,6 +291,50 @@ impl Azure {
         Ok(vmsize)
     }
 
+    /// Fetch SSH public keys from Azure Instance Metadata Service (IMDS)
+    fn fetch_ssh_keys(&self) -> Result<Vec<PublicKey>> {
+        const URL: &str = "metadata/instance/compute/publicKeys?api-version=2021-02-01";
```
Comment (prestist) [inline src/providers/microsoft/azure/mod.rs:297]: I think it might be good to add to the above comment linking to the doc's for the url referenced here. Just in case it changes or something.

File: src/providers/microsoft/azure/mod.rs [hunk 2]
```diff
@@ -351,6 +291,50 @@ impl Azure {
...
+            .client
+            .clone()
+            .header(
+                HeaderName::from_static("metadata"),
+                HeaderValue::from_static("true"),
+            )
+            .get(retry::Raw, url)
+            .send::<String>()
+            .context("failed to query IMDS for publicKeys")?
+            .ok_or_else(|| anyhow::anyhow!("IMDS did not return a publicKeys payload"))?;
```
Comment (prestist) [inline src/providers/microsoft/azure/mod.rs:310]: slick

**Review by prestist — COMMENTED** [review]
Changes lgtm, thank you for working on this, looks like you just need a comment in release notes as well.

**Comment by marmijo** [comment]
> Thanks! Do you have a docs/blog post reference for that change that we could link here?

No, I wasn't able to find much documentation related to the VM goalstate, or changes in the certificates endpoint.

> Should we add a Fixes: https://github.com/coreos/afterburn/issues/1217 in this PR?

Done!

> Completely untested but looks sane

I tested this in an Azure VM and Afterburn populated my SSH key from the IMDS as expected.

File: src/providers/microsoft/azure/mod.rs (hunk 1 above)
Comment (marmijo) [reply src/providers/microsoft/azure/mod.rs:297]: Done!

**Review by prestist — APPROVED** [review]
Thank you for the changes and +1000 for adding the tests. lgtm
