### PR TITLE
microsoft/azure: allow empty certificate chain in PKCS12 file

### LINKED ISSUE #1553: `coreos.ignition.ssh.key` failing in `kola-azure`
`coreos.ignition.ssh.key` has been failing in the `kola-azure` jenkins job since August 15, 2023 with the following error:
```
[2023-08-17T15:08:35.184Z] --- FAIL: coreos.ignition.ssh.key (331.60s)
[2023-08-17T15:08:35.184Z]         harness.go:1789: mach.Start() failed: machine "kola-975f064f-cccec36d80" failed basic checks: detected failed or stuck systemd units
```
Looking into the journal log file for the test shows:
[journal.txt](https://github.com/coreos/fedora-coreos-tracker/files/12411622/journal.txt)
[console.txt](https://github.com/coreos/fedora-coreos-tracker/files/12411627/console.txt)

```
Aug 17 19:46:17.528507 afterburn[1523]: Aug 17 19:46:17.528 INFO Fetching http://168.63.129.16/?comp=versions: Attempt #1
Aug 17 19:46:17.552714 afterburn[1523]: Aug 17 19:46:17.552 INFO Fetch successful
Aug 17 19:46:17.569624 afterburn[1523]: Aug 17 19:46:17.569 INFO Fetching http://168.63.129.16/machine/?comp=goalstate: Attempt #1
Aug 17 19:46:17.574856 afterburn[1523]: Aug 17 19:46:17.574 INFO Fetch successful
Aug 17 19:46:17.883244 afterburn[1523]: Aug 17 19:46:17.883 INFO Fetching http://168.63.129.16/machine/5c91c37d-f891-4428-93c9-81e602a91a74/a1fc44fd%2Dc611%2D4ea8%2Dbc6b%2D678f2ba3b71e.%5Fkola%2Dc954503e%2D36b448701c?comp=certificates&incarnation=1: Attempt #1
Aug 17 19:46:17.898618 afterburn[1523]: Aug 17 19:46:17.898 INFO Fetch successful
Aug 17 19:46:17.927929 afterburn[1523]: Error: failed to run
Aug 17 19:46:17.927929 afterburn[1523]: Caused by:
Aug 17 19:46:17.927929 afterburn[1523]:     0: writing ssh keys
Aug 17 19:46:17.927929 afterburn[1523]:     1: failed to convert pkcs12 blob to ssh pubkey
Aug 17 19:46:17.927929 afterburn[1523]:     2: failed to get chain from pkcs12
Aug 17 19:46:17.929015 systemd[1]: afterburn-sshkeys@core.service: Main process exited, code=exited, status=1/FAILURE
Aug 17 19:46:17.929193 systemd[1]: afterburn-sshkeys@core.service: Failed with result 'exit-code'.
Aug 17 19:46:17.934176 systemd[1]: Failed to start afterburn-sshkeys@core.service - Afterburn (SSH Keys).
Aug 17 19:46:17.942790 systemd[1]: Dependency failed for afterburn-sshkeys.target - Synchronize afterburn-sshkeys@.service template instances.
Aug 17 19:46:17.947667 systemd[1]: Dependency failed for multi-user.target - Multi-User System.
Aug 17 19:46:17.951000 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=afterburn-sshkeys@core comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Aug 17 19:46:17.952533 systemd[1]: multi-user.target: Job multi-user.target/start failed with result 'dependency'.
Aug 17 19:46:17.952960 kernel: audit: type=1130 audit(1692301577.951:80): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=afterburn-sshkeys@core comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Aug 17 19:46:17.952564 systemd[1]: afterburn-sshkeys.target: Job afterburn-sshkeys.target/start failed with result 'dependency'.
```
Afterburn fails to [convert pkcs12 blob to ssh pubkey](https://github.com/coreos/afterburn/blob/06a80b6edbe2bde448073b9b7f1b171a2507cd65/src/providers/microsoft/azure/mod.rs#L275)
Before this failure, the fetching section looked like this:
```
Aug 14 00:49:48.769452 afterburn[1511]: Aug 14 00:49:48.769 INFO Fetching http://168.63.129.16/?comp=versions: Attempt #1    
Aug 14 00:49:48.790498 afterburn[1511]: Aug 14 00:49:48.790 INFO Fetch successful                                            
Aug 14 00:49:48.809532 afterburn[1511]: Aug 14 00:49:48.809 INFO Fetching http://168.63.129.16/machine/?comp=goalstate: Attem
Aug 14 00:49:48.819160 afterburn[1511]: Aug 14 00:49:48.818 INFO Fetch successful                                            
Aug 14 00:49:48.819462 afterburn[1511]: Aug 14 00:49:48.819 WARN SSH pubkeys requested, but not provisioned for this instance
```
Which is what other test's logs look like when an SSH key IS set. So it's looking like an SSH key is being set somehow, even though one isnt specified. This is causing the `.ssh/authorized_keys.d/afterburn` file to be created and the kola test fails.

The certificates endpoint is now included in `http://168.63.129.16/machine/?comp=goalstate` so now it's being fetched and afterburn is failing directly after [fetching the certificate](https://github.com/coreos/afterburn/blob/06a80b6edbe2bde448073b9b7f1b171a2507cd65/src/providers/microsoft/azure/mod.rs#L266).

### PR DESCRIPTION
**Pull request by marmijo**
Azure is populating the certs endpoint even when an SSH key is not
provided. The certificate chain in the PKCS12 file is empty in this
case causing afterburn to fail with the current logic. Check if the
certificate chain is empty before retrieving the SSH public key
and handle this case as a valid option.

The more general `crypto/mod.rs` was updated here which also affected
the azurestack code. Update azurestack to accommodate the changes when
retrieving the SSH public key.

See: https://github.com/coreos/fedora-coreos-tracker/issues/1553

### CODE REVIEW

File: src/providers/microsoft/azure/mod.rs [hunk 1]
```diff
@@ -412,7 +412,22 @@ impl MetadataProvider for Azure {
             bail!("unexpected empty certificates endpoint");
         }
 
-        let key = self.get_ssh_pubkey(certs_endpoint)?;
+        // The certs endpoint is being populated even when the user does not supply
+        // an SSH key when created a VM. In this case the certificate chain is empty
```
Comment (dustymabe) [inline src/providers/microsoft/azure/mod.rs]:
```suggestion
        // an SSH key when creating a VM. In this case the certificate chain is empty
```

File: src/providers/microsoft/azure/mod.rs [hunk 2]
```diff
@@ -412,7 +412,22 @@ impl MetadataProvider for Azure {
...
+        // causing a failure when trying to access it. Check if the certificate chain
+        // is empty, meaning that an SSH key hasn't been provided, and only warn
+        // instead of fail.
+        let key = match self.get_ssh_pubkey(certs_endpoint) {
+            Ok(k) => k,
+            Err(e) => match e.root_cause().to_string().as_ref() {
+                "SSH public key not found in chain" => {
+                    warn!("SSH pubkeys requested, but not provisioned for this instance");
```
Comment (dustymabe) [inline src/providers/microsoft/azure/mod.rs]: I'm not sure this is the right warning to give to users, this makes it seem like we desired something (`pubkeys requested`), but couldn't find them.

File: src/providers/microsoft/crypto/mod.rs [hunk 3]
```diff
@@ -65,7 +65,14 @@ pub fn p12_to_ssh_pubkey(p12_der: &[u8]) -> Result<PublicKey> {
     // ParsedPKCS12_2 has three parts: a pkey, a main x509 cert, and a list of other
     // x509 certs. The list of other x509 certs are called the `certificate chain`
     // currently denoted as `ca`; there is only one cert in this `certificate chain`,
-    // which is the ssh public key.
+    // which is the ssh public key. The certs endpoint may still be populated even if
+    // an SSH public key hasn't been provided, which would lead to this code being
+    // executed. The certificate chain will be empty in this case, so error out and
+    // handle it further up the stack.
+    if p12.ca.is_none() {
+        return Err(anyhow!("SSH public key not found in chain"));
```
Comment (dustymabe) [inline src/providers/microsoft/crypto/mod.rs]: maybe something like:

```suggestion
        return Err(anyhow!("detected empty certificate chain"));
```

and then up the stack we give a better warning message?

File: src/providers/microsoft/azure/mod.rs (hunk 2 above)
Comment (dustymabe) [reply src/providers/microsoft/azure/mod.rs]: maybe something like:

```
No SSH keys found in the certificate chain for this instance. 
```

**Review by dustymabe — COMMENTED** [review]
mostly LGTM

Thanks for working on this!

File: src/providers/microsoft/azure/mod.rs (hunk 1 above)
Comment (marmijo) [reply src/providers/microsoft/azure/mod.rs]: Thanks for catching this one. I rewrote this comment several times.

File: src/providers/microsoft/azure/mod.rs (hunk 2 above)
Comment (marmijo) [reply src/providers/microsoft/azure/mod.rs]: That sounds like a much better warning. 
While we have this open, should I change the message a few lines up as well? I was attempting to show the warning we would have expected prior to https://github.com/coreos/fedora-coreos-tracker/issues/1553

Comment (marmijo) [reply src/providers/microsoft/azure/mod.rs]: https://github.com/coreos/afterburn/blob/f1c93ed5a6acde61f11942731766fd385f44a2e4/src/providers/microsoft/azure/mod.rs#L406

Comment (marmijo) [reply src/providers/microsoft/azure/mod.rs]: Since that warning would display when the certs endpoint doesn't exist, maybe that one could just read: 
```
SSH pubkeys not provisioned for this instance
```

File: src/providers/microsoft/crypto/mod.rs (hunk 3 above)
Comment (marmijo) [reply src/providers/microsoft/crypto/mod.rs]: SGTM

File: src/providers/microsoft/azure/mod.rs (hunk 2 above)
Comment (dustymabe) [reply src/providers/microsoft/azure/mod.rs]: sounds good to me

**Review by dustymabe — APPROVED** [review]
LGTM

File: docs/release-notes.md [hunk 4]
```diff
@@ -12,6 +12,8 @@ Major changes:
 
 Minor changes:
 
+- Fix Azure SSH key fetching when no key provisioned.
```
Comment (jlebon) [inline docs/release-notes.md]: Minor: we usually don't have a trailing period in these notes

File: src/providers/microsoft/azure/mod.rs [hunk 5]
```diff
@@ -412,7 +412,22 @@ impl MetadataProvider for Azure {
...
-        let key = self.get_ssh_pubkey(certs_endpoint)?;
+        // The certs endpoint is being populated even when the user does not supply
+        // an SSH key when creating a VM. In this case the certificate chain is empty
+        // causing a failure when trying to access it. Check if the certificate chain
+        // is empty, meaning that an SSH key hasn't been provided, and only warn
+        // instead of fail.
+        let key = match self.get_ssh_pubkey(certs_endpoint) {
+            Ok(k) => k,
+            Err(e) => match e.root_cause().to_string().as_ref() {
+                "detected empty certificate chain" => {
```
Comment (jlebon) [inline src/providers/microsoft/azure/mod.rs]: So instead of string matching errors, a more rustic way to do this is to have `get_ssh_pubkey()` return a `Result<Option<PublicKey>>`. Then, `get_ssh_pubkey()` would return `Ok(None)` for this scenario. And here, we'd do e.g.:

```rust
let key: Vec<PublicKey> = self.get_ssh_pubkeys(certs_endpoint)?.unwrap_or_default();
```

File: src/providers/microsoft/azure/mod.rs [hunk 6]
```diff
@@ -412,7 +412,22 @@ impl MetadataProvider for Azure {
...
+                    warn!("No SSH keys found in the certificate chain for this instance");
```
Comment (jlebon) [inline src/providers/microsoft/azure/mod.rs]: Is this cause for warning?

File: src/providers/microsoft/azure/mod.rs [hunk 7]
```diff
@@ -403,7 +403,7 @@ impl MetadataProvider for Azure {
         let certs_endpoint = match goalstate.certs_endpoint() {
             Some(ep) => ep,
             None => {
-                warn!("SSH pubkeys requested, but not provisioned for this instance");
+                warn!("SSH pubkeys not provisioned for this instance");
```
Comment (jlebon) [inline src/providers/microsoft/azure/mod.rs]: I think the "requested" wording in this warning refers to the fact that *something* called `afterburn --ssh-keys USER` but we couldn't find anything. And so at this layer of this stack, the warning as written previously was accurate. (Even though we know that at the FCOS layer, it's because we unconditionally run this service for the `core` user.)

File: src/providers/microsoft/azure/mod.rs (hunk 6 above)
Comment (dustymabe) [reply src/providers/microsoft/azure/mod.rs]: maybe not warn, but at least an info log statement?

File: src/providers/microsoft/azure/mod.rs (hunk 7 above)
Comment (dustymabe) [reply src/providers/microsoft/azure/mod.rs]: what does `afterburn --ssh-keys USER` imply, though?

It's hard not to look at this from the lens of FCOS where we are saying essentially "if there are SSH keys give them to me".

File: src/providers/microsoft/azure/mod.rs (hunk 6 above)
Comment (marmijo) [reply src/providers/microsoft/azure/mod.rs]: I'm not sure if it is cause for warning, but I chose to warn here because that's the behavior we expected when an SSH key wasn't supplied before this issue arose.

Comment (jlebon) [reply src/providers/microsoft/azure/mod.rs]: So to make sure I understand this: before, Azure would not offer up a certificate endpoint if no SSH keys were provided, but now it always does and instead signals no SSH keys through the certificate itself?

Comment (marmijo) [reply src/providers/microsoft/azure/mod.rs]: Basically, yes. I don't think Azure is directly signaling that no SSH key is provided through the certificate, but that's what we've found so far: that the certificate chain is empty when no SSH key is provided.

File: src/providers/microsoft/azure/mod.rs (hunk 7 above)
Comment (jlebon) [reply src/providers/microsoft/azure/mod.rs]: After looking at the code for the other providers and the history of this line, I think we should drop this warning entirely. Other providers don't warn in the case that no SSH keys were found, and AFAICT there is no reason to treat Azure differently.

File: src/providers/microsoft/azure/mod.rs (hunk 6 above)
Comment (jlebon) [reply src/providers/microsoft/azure/mod.rs]: In that case, if the new behaviour is that the certificate chain is empty when no SSH keys are present, then it should not even be considered a warning since it's completely supported to not pass an SSH key. For the same reason as the other comment, I wouldn't even `info!` it (just like other providers don't `info!` if they didn't get a key), but not strongly against. We already log something when we do write SSH keys.

`debug!()` sounds appropriate as a debugging aid if we want and could live directly in `src/providers/microsoft/crypto/mod.rs` where we `return Ok(None)` so that the calling code here can stay simple with `unwrap_or_default()` (otherwise, to log it here, we'd need to inspect the `Option` first to know if it's `None`).

File: src/providers/microsoft/azure/mod.rs (hunk 5 above)
Comment (marmijo) [reply src/providers/microsoft/azure/mod.rs]: I modified the line based on your suggestion. Since `PublicKey` doesn't implement Default, I used `unwrap_or(vec![])` instead to assign an empty vector if a None value is returned.

**Comment by marmijo** [comment]
I reworked this PR and updated the description based on the review comments.

**Comment by marmijo** [comment]
The "**Rust / Lints, pinned toolchain (pull_request)**" check is failing on `cargo fmt -- --check -l`, but I get no errors when I run this command locally on this branch. What am I missing here?

File: src/providers/microsoft/azure/mod.rs [hunk 8]
```diff
@@ -271,10 +271,13 @@ impl Azure {
...
-        let ssh_pubkey = crypto::p12_to_ssh_pubkey(&p12)
-            .context("failed to convert pkcs12 blob to ssh pubkey")?;
+        let ssh_pubkey = match crypto::p12_to_ssh_pubkey(&p12)
+            .context("failed to convert pkcs12 blob to ssh pubkey")? {
+                Some(key) => key,
+                None => return Ok(None)
+            };
 
-        Ok(ssh_pubkey)
+        Ok(Some(vec![ssh_pubkey]))
```
Comment (jlebon) [inline src/providers/microsoft/azure/mod.rs]: How about making the signature of this function as `Result<Option<PublicKey>>` and then here it'd just be

```suggestion
        Ok(Some(ssh_pubkey))
```

File: src/providers/microsoft/azure/mod.rs [hunk 9]
```diff
@@ -402,18 +405,16 @@ impl MetadataProvider for Azure {
...
 
         if certs_endpoint.is_empty() {
             bail!("unexpected empty certificates endpoint");
         }
 
-        let key = self.get_ssh_pubkey(certs_endpoint)?;
-        Ok(vec![key])
+        let key: Vec<PublicKey> = self.get_ssh_pubkey(certs_endpoint)?.unwrap_or(vec![]);
+
+        Ok(key)
```
Comment (jlebon) [inline src/providers/microsoft/azure/mod.rs]: Then this code here would remain untouched.

IOW, the lower-level `get_ssh_pubkey()` function can just focus on doing the obvious thing and this function here is where we have to deal with what our callers expect from us.

**Review by jlebon — COMMENTED** [review]
> The "Rust / Lints, pinned toolchain (pull_request)" check is failing on cargo fmt -- --check -l, but I get no errors when I run this command locally on this branch. What am I missing here?

This likely means that you're using a different version than what CI is using. You can see the version it's using in https://github.com/coreos/afterburn/blob/547c950a97b8db67d27f36e1979052f434c57f5f/.github/workflows/rust.yml#L21 and compare to yours. You don't have to match it; it should be enough to make sure you have the latest toolchain from Fedora (e.g. `dnf update rust cargo clippy rustfmt`) or from upstream if you used rustup (e.g. `rustup update`).

File: src/providers/microsoft/azure/mod.rs (hunk 9 above)
Comment (marmijo) [reply src/providers/microsoft/azure/mod.rs]: I was having a difficult time figuring out how to return a vector on `None` without inspecting the Option like 
https://github.com/coreos/afterburn/blob/c3aa867278ab4c89a6a45a3a5ee239d31ee4509e/src/providers/microsoft/azure/mod.rs#L406-L408

File: src/providers/microsoft/azure/mod.rs (hunk 8 above)
Comment (jlebon) [reply src/providers/microsoft/azure/mod.rs]: Actually, I think once we do the above, we can shrink this whole thing to just call `crypto::p12_to_ssh_pubkey(&p12).context("failed to convert pkcs12 blob to ssh pubkey")` as the final line of the function since it already matches the signature we need.

File: src/providers/microsoft/azure/mod.rs (hunk 9 above)
Comment (jlebon) [reply src/providers/microsoft/azure/mod.rs]: Oh right sorry, I missed that detail here. There's a neat Rust trick which is that `Option` actually supports iteration, in which case it'll iterate zero times or once (if the item exists). So something like `Ok(maybe_key.into_iter().collect())` should work.

Comment (marmijo) [reply src/providers/microsoft/azure/mod.rs]: Perfect, thanks! I made that change.

File: src/providers/microsoft/azure/mod.rs [hunk 10]
```diff
@@ -271,10 +271,14 @@ impl Azure {
...
 
         // convert that to the OpenSSH public key format
-        let ssh_pubkey = crypto::p12_to_ssh_pubkey(&p12)
-            .context("failed to convert pkcs12 blob to ssh pubkey")?;
+        let ssh_pubkey = match crypto::p12_to_ssh_pubkey(&p12)
+            .context("failed to convert pkcs12 blob to ssh pubkey")?
+        {
+            Some(key) => key,
+            None => return Ok(None),
+        };
```
Comment (jlebon) [inline src/providers/microsoft/azure/mod.rs]: What I mean is that all this can now be

```suggestion
        crypto::p12_to_ssh_pubkey(&p12)
            .context("failed to convert pkcs12 blob to ssh pubkey")
```

And we can remove the `Ok()` line below.

**Review by jlebon — APPROVED** [review]
One nit, LGTM otherwise!

File: src/providers/microsoft/azure/mod.rs (hunk 10 above)
Comment (marmijo) [reply src/providers/microsoft/azure/mod.rs]: Updated! Thank you.

Comment (marmijo) [reply src/providers/microsoft/azure/mod.rs]: I didnt update it properly. I'll work on it.

**Review by jlebon — APPROVED** [review]
Nice work!
